console.log("\n\nAnswer");
var car = ["subaru", "Dayz", "Mira", "nissan", "BMW"];
console.log("Is car == subaru? I predict True.");
console.log(car[0] == "subaru");
console.log("Is car == Dayz? I predict True.");
console.log(car[1] == "Dayz");
console.log("Is car == Mira? I predict True.");
console.log(car[2] == "Mira");
console.log("Is car == nissan? I predict True.");
console.log(car[3] == "nissan");
console.log("Is car == BMW? I predict True.");
console.log(car[4] == "BMW");
var num = 5;
console.log("\nB. Test 5 False conditions & we are assuming one number which value is 5:");
console.log("Is num == 2:", num == 2);
console.log("Is num < 2:", num < 2);
console.log("Is num != 5:", num != 5);
console.log("Is num > 6:", num > 6);
console.log("Is num == 0:", num == 0);
